[package]
name = "mxt-realtime"
version = "0.0.3-alpha"
edition = "2024"

[dependencies]
dotenvy = "0.15"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
axum = "0.8.9"
tokio = { version = "1.52.3", features = ["full"] }
redis-client = { path = "crates/redis-client" }
nats-client = { path = "crates/nats-client" }
realtime = { path = "crates/realtime" }
auth = { path = "crates/auth" }
event-bus = { path = "crates/event-bus" }
event-bus-jetstream = {path = "crates/event-bus-jetstream"}
support = { path = "crates/support" }
thiserror = "2.0.18"

[workspace]
members = [".", "crates/*"]
resolver = "3"
