[package]
name = "rust-web-app"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
axum = "0.8.9"
tokio = { version = "1.52.3", features = ["full"] }
redis-client = { path = "crates/redis-client" }
realtime = { path = "crates/realtime" }
auth = { path = "crates/auth" }
event-bus = { path = "crates/event-bus" }

[workspace]
members = [".", "crates/api-response", "crates/auth", "crates/realtime", "crates/redis-client", "crates/realtime", "crates/support", "crates/event-bus"]
resolver = "3"
