[package]
name = "redis-client"
version = "0.1.0"
edition = "2024"

[dependencies]
redis = { version = "0.32", features = ["tokio-comp", "sentinel", "connection-manager", "script"] }
dotenvy = "0.15"
thiserror = "2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
